workflows:
  ios-unsigned:
    name: Build iOS unsigned IPA
    environment:
      flutter: stable
      xcode: 15.0
    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..

      - name: Build unsigned IPA
        script: flutter build ios --release --no-codesign

      - name: Package IPA manually
        script: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r Runner.ipa Payload
    artifacts:
      - Runner.ipa
