workflows:
  ios-unsigned:
    name: Build iOS unsigned IPA
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build unsigned IPA
        script: flutter build ios --no-codesign --release
      - name: Package IPA manually
        script: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r Runner.ipa Payload
          artifacts:
               - Runner.ipa
